sudo: required
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
env:
  matrix:
    - DJANGO_VERSION='>=1.8,<1.9'
    - DJANGO_VERSION='>=1.9,<1.10'
    - DJANGO_VERSION='>=1.10,<1.11'
    - DJANGO_VERSION='>=1.11,<1.12'
    - DJANGO_VERSION='>=2.0,<2.1'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
install:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - wget https://github.com/apiaryio/drafter/releases/download/v3.2.7/drafter-v3.2.7.tar.gz
  - tar xvzf drafter-v3.2.7.tar.gz
  - cd drafter-v3.2.7
  - /usr/bin/python2.7 configure --shared
  - make libdrafter
  - sudo cp build/out/Release/lib.target/libdrafter.so /usr/lib/libdrafter.so
  - sudo mkdir -p /usr/include/drafter
  - sudo cp src/drafter.h /usr/include/drafter/drafter.h
  - cd ..
  - rm -rf drafter-v3.2.7/
  - rm drafter-v3.2.7.tar.gz
  - python setup.py install
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=apiblueprint_view --omit=apiblueprint_view/tests/*.py ./run_tests.py
after_success:
  - coveralls
