sudo: required
dist: trusty
language: python
python:
  - '3.5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
install:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - python setup.py install
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
  - pip install "Django>=1.11,<1.12"
  - git clone --recursive git://github.com/apiaryio/drafter.git
  - cd drafter
  - git checkout v3.2.7
  - /usr/bin/python2.7 configure --shared
  - make libdrafter
  - sudo cp build/out/Release/lib.target/libdrafter.so /usr/lib/libdrafter.so
  - sudo mkdir -p /usr/include/drafter
  - sudo cp src/drafter.h /usr/include/drafter/drafter.h
  - cd ..
  - rm -rf drafter/
script:
  - coverage run --source=apiblueprint_view --omit=apiblueprint_view/tests/*.py ./run_tests.py
after_success:
  - coveralls
