name: Build Wheels
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Wheels and Publish to PyPI
        uses: ./.github/actions/build-wheels
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          pypi-token: '${{ secrets.PYPI_TOKEN }}'
