name: Build Package (mac)
on: [push, pull_request]

jobs:
  build:
    # TODO: macos-12?
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # build the cross-compiled ARM wheels first
      - name: Build wheels for arm64
        uses: pypa/cibuildwheel@v2.16.0
        env:
          CIBW_BEFORE_BUILD: ./build-drafter-mac.sh
          CIBW_BUILD: "cp*-macosx_*"
          CIBW_SKIP: "cp36-* cp312-*"
          CIBW_ARCHS_MACOS: arm64
        with:
          package-dir: .
          output-dir: dist
          config-file: "pyproject.toml"

      # Cross compiling wheels for arm and poetry based projects
      # creates wheels with the wrong platform tag. The wheel manifest
      # + filename will get tagged with x86_64 instead of arm64.
      # Use the new `wheel tags` command to fix this.
      - name: Fix wheel tags
        run: |
          python3 -m pip install wheel
          python3 -m wheel tags --platform-tag macosx_11_0_arm64 dist/*-macosx*.whl --remove

      - name: Build wheels for x86_64
        uses: pypa/cibuildwheel@v2.16.0
        env:
          CIBW_BEFORE_BUILD: ./build-drafter-mac.sh
          CIBW_BUILD: "cp*-macosx_*"
          CIBW_SKIP: "cp36-* cp312-*"
          CIBW_ARCHS_MACOS: x86_64
        with:
          package-dir: .
          output-dir: dist
          config-file: "pyproject.toml"

      - run: ls dist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
