name: Build Wheels
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/build-wheels
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
