name: Build Wheels
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Wheels and Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: ./.github/actions/build-wheels
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          pypi-token: '${{ secrets.PYPI_TOKEN }}'
